

server:
  port: 8084


spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id : USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**
#            - Path=/hotels/**,/staffs/**  # for multiple controllers
#            - Path=/**                     # for all controllers

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**





eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true

    service-url:
      defaultZone: http://localhost:8761/eureka

# okta configuration for api gateway

okta:
  oauth2:
    issuer: https://dev-29976681.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaapfkj3avzCg7g15d7
    client-secret: wr9JaON33cKMk0DsewFw8lkm7Pk9tYAuZ3KH7XIj879K0aAknFrcAm5C1l_DJPip
    scopes: openid, profile, email, offline_access


